# Generated by Django 3.1.7 on 2021-03-29 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=12)),
                ('area', models.CharField(max_length=10)),
                ('club_name', models.CharField(max_length=12)),
                ('site_feature', models.CharField(max_length=10)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('av_device', models.CharField(max_length=40)),
                ('suitable', models.CharField(max_length=40)),
            ],
        ),
        migrations.AlterModelOptions(
            name='activityuser',
            options={'ordering': ['identity', 'name', 'department']},
        ),
    ]
