# Generated by Django 3.1.7 on 2021-03-29 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20210329_1011'),
    ]

    operations = [
        migrations.CreateModel(
            name='VenueManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a book genre (e.g. Science Fiction)', max_length=200)),
                ('extension', models.IntegerField(blank=True, null=True)),
                ('e_mail', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
