# Generated by Django 3.1.7 on 2021-03-29 02:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_venuemanager'),
    ]

    operations = [
        migrations.CreateModel(
            name='VenueInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular book across whole Venue', primary_key=True, serialize=False)),
                ('activity_name', models.TextField(help_text='Enter activity name', max_length=50)),
                ('activity_attr', models.CharField(max_length=10)),
                ('activity_category', models.CharField(max_length=10)),
                ('activity_people', models.IntegerField(blank=True, null=True)),
                ('activity_start', models.DateTimeField(blank=True, null=True)),
                ('activity_end', models.DateTimeField(blank=True, null=True)),
                ('meals_number', models.IntegerField(blank=True, null=True)),
                ('sound_control', models.BooleanField(default=False)),
                ('space_use', models.CharField(max_length=10)),
                ('user_service', models.CharField(max_length=10)),
                ('report', models.BooleanField(default=False)),
                ('message', models.TextField(help_text='Enter suggest', max_length=100)),
                ('venue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.venue')),
            ],
            options={
                'ordering': ['activity_start', 'activity_end'],
            },
        ),
    ]
