# Generated by Django 3.1.7 on 2021-03-29 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_venueinstance'),
    ]

    operations = [
        migrations.AddField(
            model_name='venueinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('m', 'Maintenance'), ('o', 'On loan'), ('a', 'Available'), ('r', 'Reserved')], default='m', help_text='Venue availability', max_length=1),
        ),
    ]
