# Generated by Django 3.1.7 on 2021-03-29 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_venueinstance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='activityuser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.activityuser'),
        ),
    ]
