# Generated by Django 3.1.7 on 2021-03-31 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_venue_activityuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='activityuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.activityuser'),
        ),
    ]
