# Generated by Django 3.1.7 on 2021-04-01 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_venueinstance_borrower'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venueinstance',
            options={'ordering': ['activity_start', 'activity_end'], 'permissions': (('can_mark_returned', 'Set venue as returned'),)},
        ),
    ]
