# Generated by Django 3.1.7 on 2021-04-01 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20210401_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venueinstance',
            name='meals_number',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
