# Generated by Django 3.1.7 on 2021-04-01 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20210401_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='venuemanager',
            field=models.ForeignKey(blank=True, help_text='Select a Venuemanager for this Venue', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.venuemanager'),
        ),
    ]
