# Generated by Django 3.1.7 on 2021-04-22 07:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_venue_venuemanager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='venuemanager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.venuemanager'),
        ),
        migrations.AlterField(
            model_name='venueinstance',
            name='activity_name',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='venueinstance',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='venueinstance',
            name='message',
            field=models.TextField(help_text=' 請輸入你的意見 ', max_length=100),
        ),
        migrations.AlterField(
            model_name='venueinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('m', 'Maintenance'), ('o', 'On loan'), ('a', 'Available'), ('r', 'Reserved')], default='m', max_length=1),
        ),
        migrations.AlterField(
            model_name='venuemanager',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
