# Generated by Django 3.1.7 on 2021-04-26 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_auto_20210426_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venueinstance',
            name='activity_attr',
            field=models.CharField(max_length=10, verbose_name='活動屬性'),
        ),
        migrations.AlterField(
            model_name='venueinstance',
            name='activity_category',
            field=models.CharField(max_length=10, verbose_name='活動類別'),
        ),
        migrations.AlterField(
            model_name='venueinstance',
            name='activity_name',
            field=models.TextField(max_length=50, verbose_name='活動名稱'),
        ),
    ]
