# Generated by Django 3.1.7 on 2021-04-27 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_auto_20210426_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venueinstance',
            name='activity_people',
            field=models.CharField(blank=True, default=100, max_length=10, null=True, verbose_name='活動人數'),
        ),
    ]
