# Generated by Django 3.1.7 on 2021-04-27 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_auto_20210427_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venueinstance',
            name='activity_people',
            field=models.CharField(blank=True, default=100, max_length=15, null=True, verbose_name='活動人數'),
        ),
    ]
