# Generated by Django 3.1.7 on 2021-05-05 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_auto_20210427_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venueinstance',
            name='sound_control',
            field=models.CharField(blank=True, default='不需要', max_length=4, verbose_name='音控志工'),
        ),
    ]
