# Generated by Django 3.1.7 on 2021-05-05 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_auto_20210505_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venueinstance',
            name='sound_control',
            field=models.BooleanField(default=False, verbose_name='音控志工'),
        ),
    ]
