# Generated by Django 3.1.7 on 2021-05-05 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_auto_20210505_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venueinstance',
            name='sound_control',
            field=models.CharField(max_length=8, verbose_name='音控志工'),
        ),
    ]
