# Generated by Django 3.1.7 on 2021-05-11 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_auto_20210511_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venueinstance',
            name='activity_end',
            field=models.DateField(blank=True, null=True, verbose_name='活動結束'),
        ),
        migrations.AlterField(
            model_name='venueinstance',
            name='activity_start',
            field=models.DateField(blank=True, null=True, verbose_name='活動開始'),
        ),
    ]
