# Generated by Django 3.1.7 on 2021-05-11 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_auto_20210511_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='icons'),
        ),
        migrations.AlterField(
            model_name='venueinstance',
            name='activity_end',
            field=models.DateField(blank=True, null=True, verbose_name='活動結束日期'),
        ),
        migrations.AlterField(
            model_name='venueinstance',
            name='activity_start',
            field=models.DateField(blank=True, null=True, verbose_name='活動開始日期'),
        ),
        migrations.AlterField(
            model_name='venueinstance',
            name='time_end',
            field=models.TimeField(blank=True, null=True, verbose_name='活動結束時間'),
        ),
        migrations.AlterField(
            model_name='venueinstance',
            name='time_start',
            field=models.TimeField(blank=True, null=True, verbose_name='活動開始時間'),
        ),
    ]
