# Generated by Django 3.1.7 on 2021-05-11 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_auto_20210511_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='c_name',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='icons', verbose_name='圖片上傳'),
        ),
    ]
